{% set name = "thriftpy" %}
{% set version = "0.3.9" %}
{% set sha256 = "309e57d97b5bfa01601393ad4f245451e989d6206a59279e56866b264a99796d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-parse-windows.patch

build:
  number: 1
  script: 
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - ply >=3.4,<4.0
    # Cython extensions not enabled on windows
    - cython  # [not win]

  run:
    - python
    - ply >=3.4,<4.0

test:
  imports:
    - thriftpy
    - thriftpy.contrib
    - thriftpy.contrib.tracking
    - thriftpy.parser
    - thriftpy.protocol
    - thriftpy.transport
    - thriftpy.transport.buffered
    - thriftpy.transport.framed
    - thriftpy.transport.memory
    # Cython extensions not enabled on windows
    - thriftpy.protocol.cybin  # [not win]

  requires:
    - tornado >=4.0,<5.0

about:
  home: https://thriftpy.readthedocs.org/
  license: MIT
  summary: 'Pure python implementation of Apache Thrift.'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - mrocklin
