# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UfC0HpSdUObNpC2El1xZvmEwZFLoYbIvqi4xDw581GjbQwJfEPHramOQVxkNJW2AiYK/k64ZF1FhvryT/pG4nfO0PRyiK9PE6ezK86lOGcV+3ALyBYEobhUmGqmkXlAMT9qbfNAORY4kIeyzYBmxzmCHydoHwLTQUFvT1ycgGrfAl1Q4/odCyIc/5KlbO+peXvWNrZ9/ZYF0TdbAj0f4tQ3YO6JTaig5QAjTrCbrRjcj20pdc/67el9GWNgLUwWEChbO/AIAaxlFz3qDhCAE0FH4l0HFfrYFsjf0Mw+9Y8wlTDYZLTGCrUJLyBJ1IV+LwxlBisO5HkH6HLaYDcLBIegPgzqnbw+1Nq1VXrvpRwXa7x28FYPn4fCpvEa11B8htx55wb+o+MxoiUkfE+7wKQNnww7huAyqicaO0b2hAvhP7QK8IX5EoDVAVdCNkAE1Xobj2cW8CRrUmMQvD/Ja84ypnrpGzKvLF3Fk+we2/XJ+OeXqx0gdj0W79vkkYBbZ8u8aHRyLb5EmsamSAvy8fm5SDcCKX0QOt+vyNro2hQcq+E0VgYnXP7GAT8hzw1/w2fqH2fIpddKNvu5mxkitc1Ix0dBxZIVImMecI6bJ68RCCFqpYmGGdlGSw2iYtKs5MwubNCfiT7kpZSwQMmU4xvV8qMfNOMwrmhh/AngvLTs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
