travis:
  secure:
    BINSTAR_TOKEN: UfC0HpSdUObNpC2El1xZvmEwZFLoYbIvqi4xDw581GjbQwJfEPHramOQVxkNJW2AiYK/k64ZF1FhvryT/pG4nfO0PRyiK9PE6ezK86lOGcV+3ALyBYEobhUmGqmkXlAMT9qbfNAORY4kIeyzYBmxzmCHydoHwLTQUFvT1ycgGrfAl1Q4/odCyIc/5KlbO+peXvWNrZ9/ZYF0TdbAj0f4tQ3YO6JTaig5QAjTrCbrRjcj20pdc/67el9GWNgLUwWEChbO/AIAaxlFz3qDhCAE0FH4l0HFfrYFsjf0Mw+9Y8wlTDYZLTGCrUJLyBJ1IV+LwxlBisO5HkH6HLaYDcLBIegPgzqnbw+1Nq1VXrvpRwXa7x28FYPn4fCpvEa11B8htx55wb+o+MxoiUkfE+7wKQNnww7huAyqicaO0b2hAvhP7QK8IX5EoDVAVdCNkAE1Xobj2cW8CRrUmMQvD/Ja84ypnrpGzKvLF3Fk+we2/XJ+OeXqx0gdj0W79vkkYBbZ8u8aHRyLb5EmsamSAvy8fm5SDcCKX0QOt+vyNro2hQcq+E0VgYnXP7GAT8hzw1/w2fqH2fIpddKNvu5mxkitc1Ix0dBxZIVImMecI6bJ68RCCFqpYmGGdlGSw2iYtKs5MwubNCfiT7kpZSwQMmU4xvV8qMfNOMwrmhh/AngvLTs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
